LabNet2021.TP4/LabNet2021.TP7.MVC/Models/PeopleSWView.cs
namespace LabNet2021.TP7.MVC.Models
{
    public class PeopleSWView
    {
        public string Name { get; set; }
        public string Height { get; set; }
        public string Eye_color { get; set; }
        public string Gender { get; set; }
    }
}

LabNet2021.TP4/LabNet2021.TP7.MVC/Models/ShippersView.cs
using System.ComponentModel.DataAnnotations;

namespace LabNet2021.TP7.MVC.Models
{
    public class ShippersView
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(40, ErrorMessage = "Longitud máxima {1} caracteres.")]
        public string Company { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [StringLength(24, ErrorMessage = "Longitud máxima {1} caracteres.")]
        public string Phone { get; set; }
    }
}

LabNet2021.TP4/LabNet2021.TP7.MVC/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace LabNet2021.TP7.MVC.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }
    }
}

LabNet2021.TP4/LabNet2021.TP7.MVC/Controllers/PeopleSWController.cs
using LabNet2021.TP7.MVC.Models;
using Newtonsoft.Json;
using StarWarsApiCSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LabNet2021.TP7.MVC.Controllers
{
    public class PeopleSWController : Controller
    {
        // GET: PeopleSW
        public async Task<ActionResult> Index()
        {
            try
            {
                string url = "https://swapi.dev/api/people/";
                var httpClient = new HttpClient();
                List<Person> peopleList = new List<Person>();

                for (int i = 1; i <= 15; i++)
                {
                    var json = await httpClient.GetStringAsync(url + i);
                    Person people = JsonConvert.DeserializeObject<Person>(json);
                    peopleList.Add(people);
                }

                List<PeopleSWView> peopleView = peopleList.Select(p => new PeopleSWView()
                {
                    Name = p.Name,
                    Height = p.Height,
                    Eye_color = p.EyeColor,
                    Gender = p.Gender
                }).ToList();

                return View(peopleView);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        // GET: PeopleSW
        //public ActionResult Index()
        //{
        //    try
        //    {
        //        var people = new Repository<Person>();
        //        List<Person> peopleList = people.GetEntities(size: int.MaxValue).ToList();

        //        List<PeopleSWView> peopleView = peopleList.Select(p => new PeopleSWView()
        //        {
        //            Name = p.Name,
        //            Height = p.Height,
        //            Eye_color = p.EyeColor,
        //            Gender = p.Gender
        //        }).ToList();

        //        return View(peopleView);
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //        return View("~/Views/Error/Index.cshtml");
        //        throw;
        //    }
        //}
    }
}

LabNet2021.TP4/LabNet2021.TP7.MVC/Controllers/ShippersController.cs
using LabNet2021.TP4.Entities;
using LabNet2021.TP4.Logic;
using LabNet2021.TP7.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace LabNet2021.TP7.MVC.Controllers
{
    public class ShippersController : Controller
    {
        ShippersLogic shippersLogic = new ShippersLogic();

        public ActionResult Index()
        {
            try
            {
                List<Shippers> shippers = shippersLogic.GetAll();

                List<ShippersView> shippersView = shippers.Select(s => new ShippersView
                {
                    ID = s.ShipperID,
                    Company = s.CompanyName,
                    Phone = s.Phone
                }).ToList();

                return View(shippersView);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        public ActionResult Insert()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        [HttpPost]
        public ActionResult Insert(ShippersView shippersView)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                Shippers shipperEntity = new Shippers
                {
                    CompanyName = shippersView.Company,
                    Phone = shippersView.Phone
                };

                shippersLogic.Add(shipperEntity);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        public ActionResult Update(int id, string company, string phone)
        {
            try
            {
                ViewBag.ID = id;
                ViewBag.Company = company;
                ViewBag.Phone = phone;

                return View("~/Views/Shippers/Insert.cshtml");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        [HttpPost]
        public ActionResult Update(ShippersView shippersView)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                Shippers shipperEntity = new Shippers
                {
                    ShipperID = shippersView.ID,
                    CompanyName = shippersView.Company,
                    Phone = shippersView.Phone
                };

                shippersLogic.Update(shipperEntity);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                shippersLogic.Delete(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("~/Views/Error/Index.cshtml");
                throw;
            }
        }
    }
}

LabNet2021.TP4/LabNet2021.TP7.MVC/Views/PeopleSW/Index.cshtml
@model List<LabNet2021.TP7.MVC.Models.PeopleSWView>
@{
    ViewBag.Title = "Personajes";
}

<h1>Personajes</h1>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Altura</th>
                <th scope="col">Color de ojos</th>
                <th scope="col">Género</th>
            </tr>
        </thead>
        @foreach (var people in Model)
        {
            <tbody>
                <tr>
                    <td>@people.Name</td>
                    <td>@people.Height cm</td>
                    <td>@people.Eye_color</td>
                    <td>@people.Gender</td>
                </tr>
            </tbody>
        }
    </table>
</div>

LabNet2021.TP4/LabNet2021.TP7.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Transportes", "Index", "Shippers", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Star Wars API", "Index", "PeopleSW", new { area = "" }, new { @class = "navbar-brand" })
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Lab .NET @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LabNet2021.TP4/LabNet2021.TP7.MVC/Views/Shippers/Index.cshtml
@model List<LabNet2021.TP7.MVC.Models.ShippersView>

@{
    ViewBag.Title = "Transportes";
}

<h1>Transportes</h1>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Empresa</th>
                <th scope="col">Teléfono</th>
            </tr>
        </thead>
        @foreach (var shipper in Model)
        {
            <tbody>
                <tr>
                    <td>@shipper.Company</td>
                    <td>@shipper.Phone</td>
                    <td>
                        @Html.ActionLink("Modificar", "Update", new { id = shipper.ID, shipper.Company, shipper.Phone }, new { @class = "btn btn-primary btn-large" })
                        @Html.ActionLink("Borrar", "Delete", new { id = shipper.ID }, new { @class = "btn btn-danger btn-large" })
                    </td>
                </tr>
            </tbody>
        }
    </table>
</div>

<div>
    @Html.ActionLink("Insertar transporte", "Insert", "Shippers", new { @class = "btn btn-success btn-large" })
</div>

LabNet2021.TP4/LabNet2021.TP7.MVC/Views/Shippers/Insert.cshtml
@model LabNet2021.TP7.MVC.Models.ShippersView

@{
    ViewBag.Title = "Transportes";
}

@{ if (ViewBag.ID == null)
    {
        <h1>Insertar transporte</h1>
        <br />

        using (Html.BeginForm("Insert", "Shippers", FormMethod.Post))
        {
            <label>Empresa:</label>
            <br />
            @Html.TextBoxFor(s => s.Company)
            <br />
            @Html.ValidationMessageFor(s => s.Company, "", new { @class = "text-danger" })
            <br />
            <label>Teléfono:</label>
            <br />
            @Html.TextBoxFor(s => s.Phone)
            <br />
            @Html.ValidationMessageFor(s => s.Phone, "", new { @class = "text-danger" })
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Guardar" />
        }
    }
    else
    {
        <h1>Modificar transporte</h1>
        <br />

        using (Html.BeginForm("Update", "Shippers", FormMethod.Post))
        {
            <label>Empresa:</label>
            <br />
            @Html.TextBoxFor(s => s.Company)
            <br />
            @Html.ValidationMessageFor(s => s.Company, "", new { @class = "text-danger" })
            <br />
            <label>Teléfono:</label>
            <br />
            @Html.TextBoxFor(s => s.Phone)
            <br />
            @Html.ValidationMessageFor(s => s.Phone, "", new { @class = "text-danger" })
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Guardar" />
        }
    }
}